data "aws_route53_zone" "zone" {
  name = "${var.dns_zone_name}."
}

# The CNAME - Canonical NAME, type allows to map on DNS name to another
# In here we map the donmain name record to the DNS of the load balancer - line 14 records
# this means that request from the domain will be forwarded to the load balancer dns name
resource "aws_route53_record" "app" {
  zone_id = data.aws_route53_zone.zone.zone_id
  name    = "${lookup(var.subdomain, terraform.workspace)}.${data.aws_route53_zone.zone.name}"
  type    = "CNAME"
  ttl     = "300"

  records = [aws_lb.api.dns_name]
}

# request certificate for the owned domain name in amazon certificate manager
resource "aws_acm_certificate" "cert" {
  domain_name = aws_route53_record.app.name
  # add certificate validation method - DNS
  validation_method = "DNS"

  lifecycle {
    create_before_destroy = true
  }
}
# Resource: aws_acm_certificate_validation
# https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation
# Create a record for each domain validation option generated by the certificate generated on line 19
# and loop through them
resource "aws_route53_record" "cert_validation" {
  for_each = {
    for dvo in aws_acm_certificate.cert.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  # create a record for each domain validation option
  # from the above for loop
  name    = each.value.name     # map with name from the for loop
  records = [each.value.record] # map with record from the for loop
  ttl     = 60
  type    = each.value.type # map with type from the for loop
  zone_id = data.aws_route53_zone.zone.zone_id
}

# validate the certificate through fullly qualified domain name, hence looping through the records
resource "aws_acm_certificate_validation" "cert" {
  certificate_arn         = aws_acm_certificate.cert.arn
  # pull the fqdn
  validation_record_fqdns = [for record in aws_route53_record.cert_validation : record.fqdn]
}